# Generated by Django 5.1.7 on 2025-03-31 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "department_name",
                    models.CharField(
                        max_length=128, unique=True, verbose_name="نام دپارتمان"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="فعال/غیر فعال"),
                ),
            ],
            options={
                "verbose_name": "دپارتمان",
                "verbose_name_plural": "دپارتمان ها",
            },
        ),
        migrations.CreateModel(
            name="Collabrations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=128, verbose_name="نام")),
                (
                    "last_name",
                    models.CharField(max_length=128, verbose_name="نام خانوادگی"),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=11, verbose_name="تلفن همراه"),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="staff_module.department",
                        verbose_name="دپارتمان",
                    ),
                ),
            ],
            options={
                "verbose_name": "همکاری",
                "verbose_name_plural": "همکاری ها",
            },
        ),
        migrations.CreateModel(
            name="HumanRecourceNeed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=128, verbose_name="نام")),
                (
                    "last_name",
                    models.CharField(max_length=128, verbose_name="نام خانوادگی"),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=11, verbose_name="تلفن همراه"),
                ),
                (
                    "job_title",
                    models.CharField(max_length=128, verbose_name="عنوان شغلی"),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="staff_module.department",
                        verbose_name="دپارتمان",
                    ),
                ),
            ],
            options={
                "verbose_name": "همکاری",
                "verbose_name_plural": "همکاری ها",
            },
        ),
    ]
