# Generated by Django 5.1.7 on 2025-04-12 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("staff_module", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="humanrecourceneed",
            options={
                "verbose_name": "درخواست منابع انسانی",
                "verbose_name_plural": "درخواست های منابع انساانی",
            },
        ),
    ]
