# Generated by Django 5.1.7 on 2025-05-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff_module", "0002_alter_humanrecourceneed_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="collabrations",
            name="resume_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="collabration/",
                verbose_name="فایل رزومه",
            ),
        ),
        migrations.AddField(
            model_name="humanrecourceneed",
            name="resume_file",
            field=models.FileField(
                blank=True, null=True, upload_to="HR/", verbose_name="فایل رزومه"
            ),
        ),
    ]
