# Generated by Django 5.1.7 on 2025-05-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff_module", "0003_collabrations_resume_file_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collabrations",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="collabrations",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="humanrecourceneed",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="humanrecourceneed",
            name="last_name",
        ),
        migrations.AddField(
            model_name="collabrations",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="ایمیل"
            ),
        ),
        migrations.AddField(
            model_name="collabrations",
            name="full_name",
            field=models.CharField(
                default="ali", max_length=128, verbose_name="نام و نام خانوادگی"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="humanrecourceneed",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="ایمیل"
            ),
        ),
        migrations.AddField(
            model_name="humanrecourceneed",
            name="full_name",
            field=models.CharField(
                default="ali", max_length=128, verbose_name="نام و نام خانوادگی"
            ),
            preserve_default=False,
        ),
    ]
