# Generated by Django 5.1.7 on 2025-05-29 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff_module", "0004_remove_collabrations_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="collabrations",
            name="explanation",
            field=models.TextField(blank=True, null=True, verbose_name="توضیحات بیشتر"),
        ),
    ]
