# Generated by Django 5.1.7 on 2025-06-02 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff_module", "0005_collabrations_explanation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="humanrecourceneed",
            name="department",
        ),
        migrations.RemoveField(
            model_name="humanrecourceneed",
            name="full_name",
        ),
        migrations.RemoveField(
            model_name="humanrecourceneed",
            name="resume_file",
        ),
        migrations.AddField(
            model_name="humanrecourceneed",
            name="company_name",
            field=models.CharField(
                default="fake", max_length=128, verbose_name="نام شرکت"
            ),
            preserve_default=False,
        ),
    ]
