# Generated by Django 5.1.7 on 2025-06-05 21:31

import datetime
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff_module", "0006_remove_humanrecourceneed_department_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="collabrations",
            name="created_at",
            field=django_jalali.db.models.jDateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 6, 5, 21, 31, 4, 354164, tzinfo=datetime.timezone.utc
                ),
                verbose_name="تاریخ ثبت همکاری",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="department",
            name="created_at",
            field=django_jalali.db.models.jDateTimeField(
                blank=True, null=True, verbose_name="تاریخ ایجاد دپارتمان"
            ),
        ),
        migrations.AddField(
            model_name="humanrecourceneed",
            name="created_at",
            field=django_jalali.db.models.jDateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 6, 5, 21, 31, 11, 216379, tzinfo=datetime.timezone.utc
                ),
                verbose_name="تاریخ ثبت درخواست",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="humanrecourceneed",
            name="explanation",
            field=models.TextField(blank=True, null=True, verbose_name="توضیحات بیشتر"),
        ),
    ]
