# Generated by Django 5.1.7 on 2025-06-23 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_module', '0007_collabrations_created_at_department_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collabrations',
            name='is_seen',
            field=models.BooleanField(default=False, verbose_name='دیده شده / نشده'),
        ),
        migrations.AddField(
            model_name='humanrecourceneed',
            name='is_seen',
            field=models.BooleanField(default=False, verbose_name='دیده شده / نشده'),
        ),
    ]
