# Generated by Django 5.1.7 on 2025-07-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_module', '0008_collabrations_is_seen_humanrecourceneed_is_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='department_icon/', verbose_name='آیکون دپارتمان'),
        ),
    ]
