# Generated by Django 5.1.7 on 2025-07-09 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_module', '0009_department_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=128, verbose_name='عنوان شغلی')),
            ],
            options={
                'verbose_name': 'عنوان شغلی',
                'verbose_name_plural': 'عنوان های شغلی',
            },
        ),
        migrations.RemoveField(
            model_name='collabrations',
            name='department',
        ),
        migrations.AddField(
            model_name='humanrecourceneed',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='HumanRecourceNeed/', verbose_name='فایل رزومه'),
        ),
        migrations.AddField(
            model_name='collabrations',
            name='job_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='staff_module.jobtitle', verbose_name='عنوان شغلی'),
        ),
    ]
