# Generated by Django 5.1.7 on 2025-03-31 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("staff_module", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Slider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slider_name",
                    models.CharField(max_length=128, verbose_name="نام اسلایدر"),
                ),
                (
                    "slider_type",
                    models.CharField(
                        choices=[], max_length=128, verbose_name="نوع اسلایدر"
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=512, verbose_name="توضیحات اسلایدر"),
                ),
                (
                    "slider_picture",
                    models.ImageField(
                        upload_to="sliders/", verbose_name="تصویر اسلایدر"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="فعال/غیر فعال"),
                ),
            ],
            options={
                "verbose_name": "اسلایدر",
                "verbose_name_plural": "اسلایدر ها",
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course_picture",
                    models.ImageField(upload_to="Courses/", verbose_name="تصویر دوره"),
                ),
                (
                    "course_name",
                    models.CharField(max_length=128, verbose_name="نام دوره"),
                ),
                (
                    "course_time_hour",
                    models.PositiveIntegerField(verbose_name="مدت زمان دوره"),
                ),
                ("about_course", models.TextField(verbose_name="درباره دوره")),
                ("course_price", models.PositiveIntegerField(verbose_name="قیمت دوره")),
                (
                    "course_level",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="سطح"
                    ),
                ),
                (
                    "course_age",
                    models.CharField(
                        choices=[], max_length=128, verbose_name="سن دوره"
                    ),
                ),
                (
                    "course_session_number",
                    models.PositiveSmallIntegerField(verbose_name="تعداد جلسات"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="فعال/غیر فعال"),
                ),
                (
                    "is_registering",
                    models.BooleanField(default=False, verbose_name="در حال ثبت نام"),
                ),
                (
                    "is_completing_registering",
                    models.BooleanField(default=False, verbose_name="تکمیل ظرفیت"),
                ),
                (
                    "course_department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="staff_module.department",
                        verbose_name="دپارتمان",
                    ),
                ),
            ],
            options={
                "verbose_name": "دوره",
                "verbose_name_plural": "دوره ها",
            },
        ),
        migrations.CreateModel(
            name="Registeration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=128, verbose_name="نام")),
                (
                    "last_name",
                    models.CharField(max_length=128, verbose_name="نام خانوادگی"),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=11, verbose_name="تلفن همراه"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="institute_module.course",
                        verbose_name="دوره",
                    ),
                ),
            ],
            options={
                "verbose_name": "ثبت نامی",
                "verbose_name_plural": "ثبت نامی ها",
            },
        ),
    ]
