# Generated by Django 5.1.7 on 2025-04-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institute_module", "0002_commentsandsuggestions"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="rank",
            field=models.FloatField(default=0.0, verbose_name="امتیاز دوره"),
        ),
    ]
