# Generated by Django 5.1.7 on 2025-05-14 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institute_module", "0003_course_rank"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="course_start_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="زمان شروع دوره"
            ),
        ),
        migrations.CreateModel(
            name="HeadlineCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "headline_name",
                    models.CharField(max_length=128, verbose_name="نام سرفصل"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="institute_module.course",
                        verbose_name="دوره",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LessonsHeadline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lesson_name",
                    models.CharField(max_length=128, verbose_name="نام درس"),
                ),
                (
                    "headline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="institute_module.headlinecourse",
                        verbose_name="سر فصل",
                    ),
                ),
            ],
        ),
    ]
