# Generated by Django 5.1.7 on 2025-05-14 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("institute_module", "0004_course_course_start_date_headlinecourse_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="headlinecourse",
            options={"verbose_name": "سر فصل", "verbose_name_plural": "سر فصل ها"},
        ),
        migrations.AlterModelOptions(
            name="lessonsheadline",
            options={
                "verbose_name": "درس سرفصل",
                "verbose_name_plural": "درس های سر فصل",
            },
        ),
    ]
