# Generated by Django 5.1.7 on 2025-05-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institute_module", "0005_alter_headlinecourse_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="course_age",
            field=models.CharField(
                choices=[
                    ("خردسال", "خردسال"),
                    ("نوجوان", "نوجوان"),
                    ("جوان", "جوان"),
                    ("بزرگسال", "بزرگسال"),
                    ("تمامی سنین", "تمامی سنین"),
                ],
                max_length=128,
                verbose_name="سن دوره",
            ),
        ),
        migrations.AlterField(
            model_name="slider",
            name="slider_type",
            field=models.CharField(
                choices=[("خبر", "خبر"), ("تخفیفات", "تخفیفات")],
                max_length=128,
                verbose_name="نوع اسلایدر",
            ),
        ),
    ]
