# Generated by Django 5.1.7 on 2025-05-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institute_module", "0006_alter_course_course_age_alter_slider_slider_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="commentsandsuggestions",
            old_name="first_name_and_last_name",
            new_name="full_name",
        ),
        migrations.RemoveField(
            model_name="registeration",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="registeration",
            name="last_name",
        ),
        migrations.AddField(
            model_name="commentsandsuggestions",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="ایمیل"
            ),
        ),
        migrations.AddField(
            model_name="registeration",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="ایمیل"
            ),
        ),
        migrations.AddField(
            model_name="registeration",
            name="full_name",
            field=models.CharField(
                default="ali", max_length=128, verbose_name="نام و نام خانوادگی"
            ),
            preserve_default=False,
        ),
    ]
