# Generated by Django 5.1.7 on 2025-05-29 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "institute_module",
            "0007_rename_first_name_and_last_name_commentsandsuggestions_full_name_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commentsandsuggestions",
            name="email",
        ),
        migrations.AddField(
            model_name="commentsandsuggestions",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="institute_module.course",
            ),
        ),
    ]
