# Generated by Django 5.1.7 on 2025-06-05 21:31

import datetime
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institute_module", "0008_remove_commentsandsuggestions_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstitueData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "initial_data",
                    models.CharField(default="اطلاعات موسسه", max_length=128),
                ),
                (
                    "successful_student",
                    models.PositiveIntegerField(
                        default=0, verbose_name="فراگیران موفق"
                    ),
                ),
                (
                    "ongoing_courses",
                    models.PositiveIntegerField(
                        default=0, verbose_name="دوره های در حال برگزاری"
                    ),
                ),
                (
                    "your_approval",
                    models.PositiveIntegerField(default=0, verbose_name="رضایت شما"),
                ),
                (
                    "experienced_teachers",
                    models.PositiveIntegerField(
                        default=0, verbose_name="اساتید مجرب ما"
                    ),
                ),
                (
                    "created_at",
                    django_jalali.db.models.jDateTimeField(
                        auto_now_add=True, verbose_name="تا تاریخ"
                    ),
                ),
            ],
            options={
                "verbose_name": "اطلاعات موسسه",
                "verbose_name_plural": "اطلاعات های موسسه",
            },
        ),
        migrations.AddField(
            model_name="commentsandsuggestions",
            name="created_at",
            field=django_jalali.db.models.jDateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 6, 5, 21, 30, 39, 153167, tzinfo=datetime.timezone.utc
                ),
                verbose_name="تاریخ ثبت نظر",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="registeration",
            name="created_at",
            field=django_jalali.db.models.jDateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 6, 5, 21, 30, 50, 45172, tzinfo=datetime.timezone.utc
                ),
                verbose_name="تاریخ ثبت نام",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="slider",
            name="created_at",
            field=django_jalali.db.models.jDateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 6, 5, 21, 30, 56, 336166, tzinfo=datetime.timezone.utc
                ),
                verbose_name="تاریخ ایجاد اسلایدر",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="course",
            name="course_start_date",
            field=django_jalali.db.models.jDateTimeField(
                blank=True, null=True, verbose_name="زمان شروع دوره"
            ),
        ),
    ]
