# Generated by Django 5.1.7 on 2025-06-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute_module', '0009_instituedata_commentsandsuggestions_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeration',
            name='is_seen',
            field=models.BooleanField(default=False, verbose_name='دیده شده / نشده'),
        ),
    ]
